{% set version = "2021.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-squarem
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/SQUAREM_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/SQUAREM/SQUAREM_{{ version }}.tar.gz
  sha256: 66e5e18ca29903e4950750bbd810f0f9df85811ee4195ce0a86d939ba8183a58

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('SQUAREM')"           # [not win]
    - "\"%R%\" -e \"library('SQUAREM')\""  # [win]

about:
  home: http://www.jhsph.edu/agingandhealth/People/Faculty_personal_pages/Varadhan.html
  license: GPL-2.0-or-later
  summary: Algorithms for accelerating the convergence of slow, monotone sequences from smooth, contraction mapping such as the EM algorithm. It can be used to accelerate any smooth, linearly convergent acceleration scheme.  A tutorial style introduction to this package is available in a vignette on the CRAN download page
    or, when the package is loaded in an R session, with vignette("SQUAREM").
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - rvalieris
